AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  TeslaAIFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/lambda_handler.handler
      Runtime: python3.12
      Environment:
        Variables:
          GROQ_API_KEY: "your-groq-api-key"
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /ask
            Method: post

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ask"
